# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('Date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_by', models.CharField(max_length=100, null=True)),
                ('otp', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
