# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 12:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20180111_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='messages',
            options={'ordering': ['-Date_created']},
        ),
    ]
